const text = document.getElementById("text");
const input = document.querySelector("input");
const te = document.getElementById("te");
const button = document.querySelector("#btn");
const loginForm = document.getElementById("loginForm");
te.style.background = " rgb(0, 191, 255)";
te.style.width = "500px";
te.style.height = "90px";
text.style.textAlign = "center";
text.style.color = "#fff";
input.style.height = "25px";
input.style.width = "295px";
input.style.margin = " 0 20px  auto";
loginForm[0].style.height = "30px";
loginForm[0].style.width = "300px";
loginForm[1].style.height = "30px";
loginForm[1].style.width = "300px";
loginForm[2].style.height = "30px";
loginForm[2].style.width = "300px";
loginForm.style.margin = "10px";
console.log(te);
console.log(text);
console.log(input);
console.log(loginForm);
